name: flutter_first_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0-70.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  get: ^4.7.2
  intl: ^0.19.0
  shimmer: ^3.0.0
  easy_date_timeline: ^1.1.3
  google_fonts: ^6.2.1
  animated_bottom_navigation_bar: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icons/
    - assets/doc/

  fonts:
    - family: SourceSansPro-Regular
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.otf

    - family: SourceSansPro-Bold
      fonts:
        - asset: assets/fonts/SourceSansPro-Bold.otf

    - family: Battambang
      fonts:
        - asset: assets/fonts/KhmerOSBattambang-Regular.ttf

    - family: Battambang-Bold
      fonts:
        - asset: assets/fonts/Battambang-Bold.ttf

    - family: Khmer
      fonts:
        - asset: assets/fonts/Khmer-Regular.ttf

    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/fa-regular-400.ttf
          style: normal

    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/fa-brands-400.ttf
          style: normal

    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/fa-solid-900.ttf
          style: normal
